---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/MavenAnsible-CICD/target/AnsibleApp.war"
        dest: "/opt/tomcat/webapps/AnsibleApp.war"
        remote_src: no
